language: python
python:
  - "2.7"
env:
- LUA=libluajit-5.1-dev
- LUA=lua5.2-dev
cache:
  - pip
  - apt
install:
- sudo apt-get install $LUA
- python setup.py install
script: python tests.py
notifications:
  irc: "irc.freenode.org#openmining"
  on_success: "never"
